version: "3.8"

services:
  app:
    image: ghcr.io/ibraam-nashaat/todo-app:latest
    ports:
      - "4000:4000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true                 # Remove old images
      - WATCHTOWER_POLL_INTERVAL=60            # Check for updates every 60 seconds
      - WATCHTOWER_INCLUDE_STOPPED=true        # Optional: include stopped containers
      - WATCHTOWER_MONITOR_ONLY=false          # Actually apply updates
