apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: ghcr.io/ibraam-nashaat/todo-app:b41cfb522a26fe1198f5380fc19b66d54c9a3248
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: todo-env
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 30
