name: Push Docker Image

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image with version tag
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/todo-app:${{ github.ref_name }} .

      - name: Push versioned Docker image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/todo-app:${{ github.ref_name }}
